device:
  name: bluejay
  stable_display_size: { width: 1080, height: 2400 }
  odm_skus:
    - GX7AS # For ROW (US, CA, TW, SG, IN): 5G Sub 6GHz
    - G1AZG # For EMEA+ (UK, DE, IE, FR, ES, IT, AU, DK, NO, SE, NL): 5G Sub 6GHz
    - GB62Z # For Verizon only: 5G mmWave + Sub 6GHz
    - GB17L # For Japan only: 5G Sub 6GHz JP2
includes:
  - common/gen6pixel.yml

filters:
  file_inclusions:
    match:
      - vendor/bin/resku_rescue_kicker

synthetic_overlays:
  SettingsGoogleSyntheticOverlay:
    resourcesToInclude:
      string:
        - battery_tip_early_replacement_summary
        - battery_tip_replacement_summary
        - battery_tip_replacement_title
        - charge_cycle_count
        - help_url_battery_replacement

  SystemUIGoogleSyntheticOverlay:
    resourcesToInclude:
      string:
        - battery_health_notify_learn_more
        - battery_management_action
        - battery_replacement_early_notify_des
        - battery_replacement_notify_des
        - battery_replacement_notify_help_url
        - battery_replacement_notify_title
