device:
  name: lynx
  stable_display_size: { width: 1080, height: 2400 }
  odm_skus:
    - GWKK3 # 5G Sub 6GHz
    - GHL1X # 5G Sub 6GHz
    - G0DZQ # 5G mmWave + Sub 6GHz
    - G82U8 # For Japan only: 5G Sub 6GHz JP
includes:
  - common/gen7pixel.yml

filters:
  file_inclusions:
    match:
      - vendor/lib64/hardware.google.bluetooth.ext@1.0.so
      - vendor/lib64/hw/hardware.google.bluetooth.ext@1.0-impl.so
