device:
  name: stallion
  stable_display_size: { width: 1080, height: 2424 }
  odm_skus:
    - GE1GQ # US: 5G Sub 6GHz
    - GV0BP # JP: 5G Sub 6GHz
    - G4H7L # ROW: 5G Sub 6GHz

includes:
  - common/gen9pixel.yml
