// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.1
// source: system/apex/proto/apex_manifest.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "apex.proto";

export interface ApexManifest {
  /**
   * APEX Name. Note that this can be different from what PackageManager sees.
   * This is used to identify an APEX and to mount under /apex directory.
   */
  name: string;
  /** Version Number */
  version: number;
  /** Pre Install Hook */
  preInstallHook: string;
  /**
   * Post Install Hook
   * This feature is not supported.
   *
   * @deprecated
   */
  postInstallHook: string;
  /** Version Name */
  versionName: string;
  /**
   * Signals whenever this APEX doesn't contain any executable code.
   * If this field is set to true, then apexd will mount this apex
   * with MS_NOEXEC flag.
   */
  noCode: boolean;
  /** List of native libs which can be used by other apexes or system. */
  provideNativeLibs: string[];
  /** List of native libs which this apex uses from other apexes or system. */
  requireNativeLibs: string[];
  /**
   * List of JNI libs.
   * linkerconfig/libnativeloader use this field so that java libraries can
   * load JNI libraries in the same apex.
   * This is supposed to be filled by the build system with libraries which are
   * marked as "is_jni: true" from the list of "native_shared_libs".
   */
  jniLibs: string[];
  /**
   * Deprecated.
   * List of libs required that are located in a shared libraries APEX.  The
   * Android platform only checks whether this list is non-empty, and by default
   * the Android build system never sets this. This field can be used when
   * producing or processing an APEX using libraries in /apex/sharedlibs (see
   * `provideSharedApexLibs` field) to store some information about the
   * libraries.
   *
   * @deprecated
   */
  requireSharedApexLibs: string[];
  /**
   * Deprecated.
   * Whether this APEX provides libraries to be shared with other APEXs. This
   * causes libraries contained in the APEX to be made available under
   * /apex/sharedlibs .
   *
   * @deprecated
   */
  provideSharedApexLibs: boolean;
  /** Exists only for compressed APEX */
  capexMetadata:
    | ApexManifest_CompressedApexMetadata
    | undefined;
  /** Indicates that this APEX can be updated without rebooting device. */
  supportsRebootlessUpdate: boolean;
  /** VNDK version for apexes depending on a specific version of VNDK libs. */
  vndkVersion: string;
  /**
   * Deprecated.
   * Whether this vendor APEX needs to be activated in bootstrap phase.
   * For new APEX, please use `bootstrap` instead.
   * Vendor APEX become bootstrap APEX if either `vendorBootstrap`
   * or `bootstrap` is set to true.
   *
   * @deprecated
   */
  vendorBootstrap: boolean;
  /** Whether this APEX needs to be activated in bootstrap phase. */
  bootstrap: boolean;
}

export interface ApexManifest_CompressedApexMetadata {
  /**
   * Valid only for compressed APEX. This field contains the root digest of
   * the original_apex contained inside CAPEX.
   */
  originalApexDigest: string;
}

function createBaseApexManifest(): ApexManifest {
  return {
    name: "",
    version: 0,
    preInstallHook: "",
    postInstallHook: "",
    versionName: "",
    noCode: false,
    provideNativeLibs: [],
    requireNativeLibs: [],
    jniLibs: [],
    requireSharedApexLibs: [],
    provideSharedApexLibs: false,
    capexMetadata: undefined,
    supportsRebootlessUpdate: false,
    vndkVersion: "",
    vendorBootstrap: false,
    bootstrap: false,
  };
}

export const ApexManifest: MessageFns<ApexManifest> = {
  encode(message: ApexManifest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.version !== 0) {
      writer.uint32(16).int64(message.version);
    }
    if (message.preInstallHook !== "") {
      writer.uint32(26).string(message.preInstallHook);
    }
    if (message.postInstallHook !== "") {
      writer.uint32(34).string(message.postInstallHook);
    }
    if (message.versionName !== "") {
      writer.uint32(42).string(message.versionName);
    }
    if (message.noCode !== false) {
      writer.uint32(48).bool(message.noCode);
    }
    for (const v of message.provideNativeLibs) {
      writer.uint32(58).string(v!);
    }
    for (const v of message.requireNativeLibs) {
      writer.uint32(66).string(v!);
    }
    for (const v of message.jniLibs) {
      writer.uint32(74).string(v!);
    }
    for (const v of message.requireSharedApexLibs) {
      writer.uint32(82).string(v!);
    }
    if (message.provideSharedApexLibs !== false) {
      writer.uint32(88).bool(message.provideSharedApexLibs);
    }
    if (message.capexMetadata !== undefined) {
      ApexManifest_CompressedApexMetadata.encode(message.capexMetadata, writer.uint32(98).fork()).join();
    }
    if (message.supportsRebootlessUpdate !== false) {
      writer.uint32(104).bool(message.supportsRebootlessUpdate);
    }
    if (message.vndkVersion !== "") {
      writer.uint32(114).string(message.vndkVersion);
    }
    if (message.vendorBootstrap !== false) {
      writer.uint32(120).bool(message.vendorBootstrap);
    }
    if (message.bootstrap !== false) {
      writer.uint32(128).bool(message.bootstrap);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApexManifest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApexManifest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.version = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.preInstallHook = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.postInstallHook = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.versionName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.noCode = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.provideNativeLibs.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.requireNativeLibs.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.jniLibs.push(reader.string());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.requireSharedApexLibs.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.provideSharedApexLibs = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.capexMetadata = ApexManifest_CompressedApexMetadata.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.supportsRebootlessUpdate = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.vndkVersion = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.vendorBootstrap = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 128) {
            break;
          }

          message.bootstrap = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApexManifest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      preInstallHook: isSet(object.preInstallHook) ? globalThis.String(object.preInstallHook) : "",
      postInstallHook: isSet(object.postInstallHook) ? globalThis.String(object.postInstallHook) : "",
      versionName: isSet(object.versionName) ? globalThis.String(object.versionName) : "",
      noCode: isSet(object.noCode) ? globalThis.Boolean(object.noCode) : false,
      provideNativeLibs: globalThis.Array.isArray(object?.provideNativeLibs)
        ? object.provideNativeLibs.map((e: any) => globalThis.String(e))
        : [],
      requireNativeLibs: globalThis.Array.isArray(object?.requireNativeLibs)
        ? object.requireNativeLibs.map((e: any) => globalThis.String(e))
        : [],
      jniLibs: globalThis.Array.isArray(object?.jniLibs) ? object.jniLibs.map((e: any) => globalThis.String(e)) : [],
      requireSharedApexLibs: globalThis.Array.isArray(object?.requireSharedApexLibs)
        ? object.requireSharedApexLibs.map((e: any) => globalThis.String(e))
        : [],
      provideSharedApexLibs: isSet(object.provideSharedApexLibs)
        ? globalThis.Boolean(object.provideSharedApexLibs)
        : false,
      capexMetadata: isSet(object.capexMetadata)
        ? ApexManifest_CompressedApexMetadata.fromJSON(object.capexMetadata)
        : undefined,
      supportsRebootlessUpdate: isSet(object.supportsRebootlessUpdate)
        ? globalThis.Boolean(object.supportsRebootlessUpdate)
        : false,
      vndkVersion: isSet(object.vndkVersion) ? globalThis.String(object.vndkVersion) : "",
      vendorBootstrap: isSet(object.vendorBootstrap) ? globalThis.Boolean(object.vendorBootstrap) : false,
      bootstrap: isSet(object.bootstrap) ? globalThis.Boolean(object.bootstrap) : false,
    };
  },

  toJSON(message: ApexManifest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.preInstallHook !== "") {
      obj.preInstallHook = message.preInstallHook;
    }
    if (message.postInstallHook !== "") {
      obj.postInstallHook = message.postInstallHook;
    }
    if (message.versionName !== "") {
      obj.versionName = message.versionName;
    }
    if (message.noCode !== false) {
      obj.noCode = message.noCode;
    }
    if (message.provideNativeLibs?.length) {
      obj.provideNativeLibs = message.provideNativeLibs;
    }
    if (message.requireNativeLibs?.length) {
      obj.requireNativeLibs = message.requireNativeLibs;
    }
    if (message.jniLibs?.length) {
      obj.jniLibs = message.jniLibs;
    }
    if (message.requireSharedApexLibs?.length) {
      obj.requireSharedApexLibs = message.requireSharedApexLibs;
    }
    if (message.provideSharedApexLibs !== false) {
      obj.provideSharedApexLibs = message.provideSharedApexLibs;
    }
    if (message.capexMetadata !== undefined) {
      obj.capexMetadata = ApexManifest_CompressedApexMetadata.toJSON(message.capexMetadata);
    }
    if (message.supportsRebootlessUpdate !== false) {
      obj.supportsRebootlessUpdate = message.supportsRebootlessUpdate;
    }
    if (message.vndkVersion !== "") {
      obj.vndkVersion = message.vndkVersion;
    }
    if (message.vendorBootstrap !== false) {
      obj.vendorBootstrap = message.vendorBootstrap;
    }
    if (message.bootstrap !== false) {
      obj.bootstrap = message.bootstrap;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApexManifest>, I>>(base?: I): ApexManifest {
    return ApexManifest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApexManifest>, I>>(object: I): ApexManifest {
    const message = createBaseApexManifest();
    message.name = object.name ?? "";
    message.version = object.version ?? 0;
    message.preInstallHook = object.preInstallHook ?? "";
    message.postInstallHook = object.postInstallHook ?? "";
    message.versionName = object.versionName ?? "";
    message.noCode = object.noCode ?? false;
    message.provideNativeLibs = object.provideNativeLibs?.map((e) => e) || [];
    message.requireNativeLibs = object.requireNativeLibs?.map((e) => e) || [];
    message.jniLibs = object.jniLibs?.map((e) => e) || [];
    message.requireSharedApexLibs = object.requireSharedApexLibs?.map((e) => e) || [];
    message.provideSharedApexLibs = object.provideSharedApexLibs ?? false;
    message.capexMetadata = (object.capexMetadata !== undefined && object.capexMetadata !== null)
      ? ApexManifest_CompressedApexMetadata.fromPartial(object.capexMetadata)
      : undefined;
    message.supportsRebootlessUpdate = object.supportsRebootlessUpdate ?? false;
    message.vndkVersion = object.vndkVersion ?? "";
    message.vendorBootstrap = object.vendorBootstrap ?? false;
    message.bootstrap = object.bootstrap ?? false;
    return message;
  },
};

function createBaseApexManifest_CompressedApexMetadata(): ApexManifest_CompressedApexMetadata {
  return { originalApexDigest: "" };
}

export const ApexManifest_CompressedApexMetadata: MessageFns<ApexManifest_CompressedApexMetadata> = {
  encode(message: ApexManifest_CompressedApexMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.originalApexDigest !== "") {
      writer.uint32(10).string(message.originalApexDigest);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApexManifest_CompressedApexMetadata {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApexManifest_CompressedApexMetadata();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.originalApexDigest = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApexManifest_CompressedApexMetadata {
    return { originalApexDigest: isSet(object.originalApexDigest) ? globalThis.String(object.originalApexDigest) : "" };
  },

  toJSON(message: ApexManifest_CompressedApexMetadata): unknown {
    const obj: any = {};
    if (message.originalApexDigest !== "") {
      obj.originalApexDigest = message.originalApexDigest;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApexManifest_CompressedApexMetadata>, I>>(
    base?: I,
  ): ApexManifest_CompressedApexMetadata {
    return ApexManifest_CompressedApexMetadata.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApexManifest_CompressedApexMetadata>, I>>(
    object: I,
  ): ApexManifest_CompressedApexMetadata {
    const message = createBaseApexManifest_CompressedApexMetadata();
    message.originalApexDigest = object.originalApexDigest ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
